# taskpilot/agents/coordinator_agent.py
"""CoordinatorAgent – orchestrates the other agents.

Typical flow:
    1. Parse free‑form user input into :class:`Task` objects (TaskAgent).
    2. Rank those tasks by priority (PriorityAgent).
    3. Generate a simple schedule (SchedulerAgent).

The ``run`` method returns the schedule dictionary generated by
``SchedulerAgent``.  In a full application this could be formatted for UI
output, saved to a database, etc.
"""

from __future__ import annotations

from ..database.db import create_tables, add_task, list_tasks

# Local imports – the agents live in the same package.
from .task_agent import TaskAgent
from .priority_agent import PriorityAgent
from .scheduler_agent import SchedulerAgent


class CoordinatorAgent:
    """High‑level orchestrator for TaskPilot.

    The public ``run`` method accepts a raw user string and returns a schedule
    dictionary mapping dates (ISO ``YYYY‑MM‑DD``) to lists of task titles.
    """

    def __init__(self) -> None:
        # Instances of the sub‑agents – stateless, but keeping them as objects
        # makes future extension (e.g., injecting configuration) easier.
        self.task_agent = TaskAgent()
        self.priority_agent = PriorityAgent()
        self.scheduler_agent = SchedulerAgent()

    # Updated run method with persistence
    def run(self, user_input: str) -> Dict[str, List[str]]:
        """Process ``user_input`` and produce a schedule.

        Steps:
        1. Extract :class:`Task` objects.
        2. Persist tasks to the SQLite database.
        3. Convert them to plain dictionaries (title, deadline, estimated_hours).
        4. Rank them by priority.
        5. Generate a daily schedule.
        """
        # 1. Extract tasks – returns a list of Task dataclass instances.
        tasks = self.task_agent.extract_tasks(user_input)

        # Ensure database tables exist
        create_tables()
        # 2. Persist newly extracted tasks
        for task in tasks:
            try:
                add_task(task)
            except Exception:
                # Ignore duplicate insertion errors for now
                pass

        # 3. Load all tasks from the DB (including previously added ones)
        all_tasks = list_tasks()

        # 4. Convert to simple dicts for downstream agents
        task_dicts: List[Dict[str, Any]] = []
        for t in all_tasks:
            task_dicts.append(
                {
                    "title": t.title,
                    "deadline": t.deadline,
                    "estimated_hours": getattr(t, "estimated_hours", 1.0),
                }
            )

        # 5. Rank / assign priority.
        ranked = self.priority_agent.rank_tasks(task_dicts)

        # 6. Generate schedule.
        schedule = self.scheduler_agent.generate_schedule(ranked)
        return schedule

# Export a ready‑to‑use instance for simple imports.
coordinator = CoordinatorAgent()
